
services:
  db:
    image: postgres:latest
    container_name: db
    env_file: 
      - .env
    ports:
      - "5432:5432"
    networks:
      - app_network
    volumes:
      - db_data:/var/lib/postgresql/data

  fastapi:
    build: ./backend  # Use the Dockerfile inside the backend directory
    ports:
      - "8000:8000"  # Expose FastAPI on port 8000
    env_file: 
      - .env
    volumes:
      - ./backend:/app  # Mount the backend directory
    networks:
      - app_network

  streamlit:
    build: ./ui  # Use the Dockerfile inside the ui directory
    ports:
      - "8501:8501"  # Expose Streamlit on port 8501
    volumes:
      - ./ui:/app
    networks:
      - app_network
    depends_on:
      - fastapi 

  neo4j:
    image: neo4j:latest
    container_name: neo4j
    ports:
      - "7474:7474" # Neo4j Browser
      - "7687:7687" # Bolt protocol
    env_file: 
      - .env
    networks:
      - app_network


volumes:
  db_data:  # Volume to store PostgreSQL data persistently


networks:
  app_network:
    driver: bridge